name: todo_list_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  json_annotation: ^4.8.1
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  shared_preferences: ^2.1.2
  firebase_database: ^10.2.3
  provider: ^6.0.5
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mobx_codegen: ^2.3.0
  build_runner: ^2.4.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
