// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG7E7i4dvYel13hwc1KEUrqg2Qvj_lniA',
    appId: '1:1016924941512:web:0835936146016078df89fd',
    messagingSenderId: '1016924941512',
    projectId: 'todolist-28239',
    authDomain: 'todolist-28239.firebaseapp.com',
    storageBucket: 'todolist-28239.appspot.com',
    measurementId: 'G-C561KER04C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2QmqjhEskCY0f4Ie43irWa4deBcoXGpI',
    appId: '1:1016924941512:android:22911f59adbb22fadf89fd',
    messagingSenderId: '1016924941512',
    projectId: 'todolist-28239',
    storageBucket: 'todolist-28239.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9po6NehHlskUZHRhrDeC7vzHc6wweYH4',
    appId: '1:1016924941512:ios:93addf5630099928df89fd',
    messagingSenderId: '1016924941512',
    projectId: 'todolist-28239',
    storageBucket: 'todolist-28239.appspot.com',
    iosClientId: '1016924941512-e22nfbqpjcuhj8q6kusahossebhhthcg.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9po6NehHlskUZHRhrDeC7vzHc6wweYH4',
    appId: '1:1016924941512:ios:3ff8f3bad9bfefb0df89fd',
    messagingSenderId: '1016924941512',
    projectId: 'todolist-28239',
    storageBucket: 'todolist-28239.appspot.com',
    iosClientId: '1016924941512-v313cer6tduvsnsonmg1vtmfid1r81a0.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineShopApp.RunnerTests',
  );
}
